### ISSUE TITLE
HTTP links on HTTPS page

### ISSUE THREAD

**Issue by pcolmer** [Linaro/platforms-website#10]
<a target="_self" href="http://releases.linaro.org/reference-platform/enterprise/latest/?utm_source=platforms.linaro&amp;utm_medium=submenu" class="dropdown-item " title="">Downloads </a>, <a href="http://www.linaro.org">Linaro</a>, <a href="http://www.linaro.org">Linaro</a>, <a class="footer-element" href="http://releases.linaro.org/reference-platform/enterprise/latest/?utm_source=platforms.linaro&amp;utm_medium=submenu">Downloads</a>

Please change the links to drop the protocol (i.e. drop `http:`) so that the browser automatically uses the same protocol as being used with platforms.l.o. Since we force HTTPS, it means that the URL will automatically change to be HTTPS for these links.

**Comment by kylekirkby** [comment]
I've dropped the protocol from the navbar item.

**Comment by pcolmer** [comment]
There are some other HTTP links on the front page …

Under "License", the link for Linaro and Creative Commons is HTTP.

In the footer, the link for Downloads is HTTP.

The Facebook link is HTTP.

It might be worth doing a quick text search of the repo to sanity check any links that are explicitly http://.

Thanks :)
